wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.9.4
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.3
batch_size:
  desc: null
  value: 32
conv1:
  desc: null
  value: 64
conv2:
  desc: null
  value: 128
conv3:
  desc: null
  value: 256
conv4:
  desc: null
  value: 256
drop1:
  desc: null
  value: 0.49146980295488907
drop2:
  desc: null
  value: 0.42186973081745616
epochs:
  desc: null
  value: 43
l2_rate:
  desc: null
  value: 0.008917357677578187
lr:
  desc: null
  value: 0.0006269802355768629
