wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.9.4
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.3
batch_size:
  desc: null
  value: 32
conv1:
  desc: null
  value: 64
conv2:
  desc: null
  value: 128
conv3:
  desc: null
  value: 256
conv4:
  desc: null
  value: 256
drop1:
  desc: null
  value: 0.37252636612915996
drop2:
  desc: null
  value: 0.15310548184650682
epochs:
  desc: null
  value: 83
l2_rate:
  desc: null
  value: 0.0072647335838471865
lr:
  desc: null
  value: 0.0006321013345214352
