wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.9.4
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.3
batch_size:
  desc: null
  value: 32
conv1:
  desc: null
  value: 32
conv2:
  desc: null
  value: 128
conv3:
  desc: null
  value: 256
conv4:
  desc: null
  value: 512
drop1:
  desc: null
  value: 0.3763652174992007
drop2:
  desc: null
  value: 0.47600733958493263
epochs:
  desc: null
  value: 48
l2_rate:
  desc: null
  value: 0.006437917387882628
lr:
  desc: null
  value: 0.000703672642474268
