wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.9.4
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.3
batch_size:
  desc: null
  value: 64
conv1:
  desc: null
  value: 32
conv2:
  desc: null
  value: 128
conv3:
  desc: null
  value: 256
conv4:
  desc: null
  value: 512
drop1:
  desc: null
  value: 0.4844329561048287
drop2:
  desc: null
  value: 0.34323173225690845
epochs:
  desc: null
  value: 99
l2_rate:
  desc: null
  value: 0.0015104008432023483
lr:
  desc: null
  value: 0.0007278193011457575
