wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.9.4
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.3
batch_size:
  desc: null
  value: 64
conv1:
  desc: null
  value: 32
conv2:
  desc: null
  value: 64
conv3:
  desc: null
  value: 256
conv4:
  desc: null
  value: 128
drop1:
  desc: null
  value: 0.1921660792094922
drop2:
  desc: null
  value: 0.3877874205715762
epochs:
  desc: null
  value: 89
l2_rate:
  desc: null
  value: 0.0005386852187074074
lr:
  desc: null
  value: 0.0008914792588162499
