wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.9.4
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.3
batch_size:
  desc: null
  value: 32
conv1:
  desc: null
  value: 32
conv2:
  desc: null
  value: 64
conv3:
  desc: null
  value: 128
conv4:
  desc: null
  value: 256
drop1:
  desc: null
  value: 0.20013878959012624
drop2:
  desc: null
  value: 0.12022177760254342
epochs:
  desc: null
  value: 84
l2_rate:
  desc: null
  value: 0.005234739696960674
lr:
  desc: null
  value: 0.000920663640626804
